### ISSUE TITLE
Ch. 5 - The Colchester Catch

### ISSUE THREAD

**Issue by dwanneruchi** [rlvaugh/Impractical_Python_Projects#5]
Firstly, great hidden message :) 

When working through this I got a bit stuck on the example message provided so wanted to share that feedback. 

Example provided: 

> T**h**e cold t**e**a didn't p**l**ease the o**l**d finicky w**o**man 

Output: H-E-L-L-O

You stated this would be an example of input = 2, so from this I assumed that we should just always start with the first word in a sentence and take the nth character, then increment by the input to the next nth word and take the nth character. 

In the actual hidden message you have to increment by the input from the beginning in order to properly solve, which changed my underlying function. This would also mean the above example would look like this: 

> The c**o**ld tea d**i**dn't please t**h**e old f**i**nicky woma.

Output: O-I-H-I (almost my home state!)

Maybe I missed something here, but wanted to point it out as it threw me off a bit in solving for the colchester_msg.txt file. 

Thanks, really enjoying these problems! It is a great book!

**Comment by rlvaugh** [comment]
It should have read: "So, the cold tea didn't please the old finicky woman" so you are right to be confused. There is an errata on the book's No Starch website, where you downloaded the code (https://nostarch.com/impracticalpythonprojects); there are a few other typos, so you might want to check it out. We should be correcting this in the third printing. Sorry for the confusion and the late response.
