### ISSUE TITLE
Bug in Chapter 2 - dictionary_cleanup_practice.py

### ISSUE THREAD

**Issue by neerajsamtani** [rlvaugh/Impractical_Python_Projects#6]
The script doesn't work as intended if two single letter words (except 'a' and 'i') are consecutive in the list/dictionary file.

**Comment by rlvaugh** [comment]
Thank you for catching this and sorry for the late response.
![Capture](https://user-images.githubusercontent.com/31315095/67586766-03690200-f718-11e9-8175-88c529430ebd.JPG)

**Comment by neerajsamtani** [comment]
Thanks!
