### ISSUE TITLE
Chapter 7: Project 14: Listing 7-10 (Second Printing)

### ISSUE THREAD

**Issue by alexpovel** [rlvaugh/Impractical_Python_Projects#7]
In the line prefaced by bullet-point number *7*, it reads:

```python
next_try[lock_wheel] = randint(0, len(combo) - 1)
```

which means that we try a digit on that index that depends on the combination length, instead of just picking a digit from 0 to 9.
It works in the example, since the combination is 10 digits long, so that the line evaluates to `randint(0, 10 - 1)`.
However, it fails to solve all combinations where

```python
any([digit > len(combo) - 1 for digit in combo])
```

holds true, e.g. an 8 occurs in a combination of length 5.

While writing this, I noticed the issue is fixed [here](https://github.com/rlvaugh/Impractical_Python_Projects/blob/master/Chapter_7/safe_cracker.py#L32).

I am leaving this issue for others to find and as a reminder that this should be corrected in future print versions.

**Comment by rlvaugh** [comment]
Thanks. The project was written for a 10-digit combo, but just before going to print the editor suggested making it work for any combo. I forgot to update this line. It will be corrected in the 3rd edition.

Please check out the webpage for other errata: https://nostarch.com/impracticalpythonprojects.
